dashboard:

reporter:
  logs_basedir: "sshfs://viv@192.168.0.198:/home/viv/dwarfdisk/Backup/logs/"
  repos_basedir: "ssh://viv@192.168.0.198/home/viv/dwarfdisk/Backup"

  discord:
    webhook: "https://discord.com/api/webhooks/1121501560833323091/dGZjhM35M6VheXTGJFFxeLjpkQpt6WLi7zfCgbUdVqIMeaPB4Sn8Y4w8PeqNI-Iy1F9H"
    webhook_user: "Borg backup dashboard"
    message: "**{} Backups failed**:\n\n{}\nSee [web dashboard](http://127.0.0.1:3000) for details"
    message_bkup: "- **{}**: Failed with status `{}` on {}\n"

repos:
  "dwarfserver":
    "repo_path": "dwarfserver"
    "log_path": "dwarfserver"
    "repo_pwd": "backup"
    "script": "script"

  "mediadwarf":
    "repo_path": "mediadwarf"
    "log_path": "mediadwarf"
    "repo_pwd": "backup"
    "script": "script"

  "domodwarf":
    "repo_path": "domodwarf"
    "log_path": "domodwarf"
    "repo_pwd": "backup"
    "script": "script"

  "monidwarf":
    "repo_path": "monidwarf"
    "log_path": "monidwarf"
    "repo_pwd": "backup"
    "script": "script"

  "dwarfnas":
    "repo_path": "ssh://viv@192.168.0.198/srv/dev-disk-by-uuid-cfcc839a-b20f-4d7f-934a-16cb90e6dde0/Backup/dwarfnas/omvbackup/borgbackup"
    "repo_pwd": "nasbackup"
    "script": "script"
