dashboard:
  # This needs to be updated to the git repo clone path
  reporter_path: "./reporter/.pixi/envs/default/bin/borgdash-reporter"
  rescan_timeout_ms: 300000
  sshfs_mount_uptime_ms: 300000

reporter:
  # If not on osx with brew installation of borg, needs update
  borg_path: "/opt/homebrew/bin/borg"
  report_path: "/tmp/borgdash_report.json"
  crontab_path: "/tmp/borgdash.cron"
  dedupe_path: "/tmp/borgdash_dedupe.json"

  logs_basedir: "sshfs://user@192.168.0.1:/home/Backup/logs"
  repos_basedir: "ssh://user@192.168.0.1/home/Backup"

  discord:
    webhook: "https://discord.com/api/webhooks/xxxxxx/yyyyyy-zzzzz"
    webhook_user: "Borg backup dashboard"
    # First {}: backups count, second: list of message_bkup for each failed bkup
    message: "**{} Backups failed**:\n\n{}\nSee [web dashboard](http://127.0.0.1:3000) for details"
    # First {}: backup name, second: status, third: date/time
    message_bkup: "- **{}**: Failed with status `{}` on {}\n"

repos:
  "remote1":
    "repo_path": "remote1"
    "log_path": "remote1"
    "repo_pwd": "pass"

  "remote2":
    "repo_path": "remote2"
    "log_path": "remote2"
    "repo_pwd": "pass"
