dashboard:
  # Path to the reporter binary to run to regenerate the borg report
  reporter_path: "/reporter/.pixi/envs/default/bin/borgdash-reporter"
  # UI Timeout for borg report generation.
  rescan_timeout_ms: 300000
  # Time to keep sshfs mounts. Past this time they'll be remounted at next log display
  sshfs_mount_uptime_ms: 6000000

reporter:
  # Path where to store the borg report containing the report data
  report_path: "/etc/borgdash_report.json"
  # Path to the borg binary
  borg_path: "/usr/bin/borg"
  # Path to store the cronab file
  crontab_path: "/etc/borgdash.cron"
  # Crontab formatted schedule to launch the reporter scan. If empty or not specified periodic run is disabled
  # schedule: "0 6 * * *"

  # Base directory for relative paths specified in repos config's 'log_path'.
  # Can be an sshfs mount, requiring keys to be configured like for ssh remote repo
  # Prepended if the repo path is relative (doesn't start with /)
  # repos_basedir: "sshfs://user@192.168.0.10:/repos"
  logs_basedir: "/repos_logs"
  # Base directory for relative paths specified in repos config's `repo path`.
  # Can be ssh url, but ssh keys must be authorized on hosts to enable password less connection.
  # Used if the repo path is relative (doesn't start with / or ssh://)
  # repos_basedir: "ssh://user@192.168.0.10/repos"
  repos_basedir: "/repos"

  # Enable alarming on discord channel for failed backups 90/
  # discord:
  #   webhook: "https://discord.com/api/webhooks/xxxxxxxx/yyyyy"
  #   webhook_user: "Borg backup dashboard"
  #   # First {}: backups count, second: list of message_bkup for each failed bkup
  #   message: "**{} Backups failed**:\n\n{}\nSee [web dashboard](http://127.0.0.1:3000) for details"
  #   # First {}: backup name, second: status, third: date/time
  #   message_bkup: "- **{}**: Failed with status `{}` on {}\n"
# repos:
#   # Repo  name
#   "repo_test":
#     # Repo absolute path or relative to repos_basedir, this is where the borg archives for this repo will be
#     # searched for
#     "repo_path": "/repo_test"
#     # Optional repo logs absolute path, or relative to the main logs_basedir. If logs are there, they're expected
#     # to contain the borg command(s) output for the archive creation
#     "log_path": "/repo_test_logs"
#     # Repo password if any
#     "repo_pwd": "backup"
#     # Optional: Command/script to run to manually start a backup.
#     "script": "script"
